CREATE TABLE USUARIO(
    ID SERIAL NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,

    PRIMARY KEY (ID)
);

INSERT INTO USUARIO ( ID,NOME, EMAIL) VALUES (1, 'Giovanne', 'giovanne@dev.com')