CREATE TABLE TOPICO(
    ID SERIAL NOT NULL,
    TITULO VARCHAR(50) NOT NULL,
    MENSAGEM VARCHAR(300) NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CURSO_ID BIGINT NOT NULL,
    AUTOR_ID BIGINT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID),
    FOREIGN KEY (AUTOR_ID) REFERENCES USUARIO(ID)
);