CREATE TABLE RESPOSTA(
    ID SERIAL NOT NULL,
    MENSAGEM VARCHAR(300) NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    TOPICO_ID BIGINT NOT NULL,
    AUTOR_ID BIGINT NOT NULL,
    SOLUCAO BOOLEAN NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (TOPICO_ID) REFERENCES TOPICO(ID),
    FOREIGN KEY (AUTOR_ID) REFERENCES USUARIO(ID)
);