ALTER TABLE USUARIO ADD COLUMN PASSWORD VARCHAR(100) NOT NULL;


INSERT INTO USUARIO ( ID,NOME, EMAIL, PASSWORD) VALUES (1, 'Giovanne', 'giovanne@dev.com', '$2a$12$1UxIolUB5l/sIX3dsqytqObzqiUeE1YOiJSBqai5GXqRzhfgWUoE6')


